[project]
name = "instagram-unliker"
version = "1.0.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pillow>=11.1.0",
    "pycryptodomex>=3.21.0",
    "pydantic>=2.10.6",
    "pyotp>=2.9.0",
    "pysocks>=1.7.1",
    "requests>=2.32.3",
    "urllib3>=2.3.0",
]
